### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by decathorpe** [brettcannon/python-launcher#401]
Version 1.0.0 was released ~3 years ago, so the dependencies for it are increasingly outdated. This is starting to cause issues, for example, it's hard to keep the Fedora Linux package for python-launcher in good shape because it pulls in increasingly old versions of dependencies compared to the current state of crates.io / git HEAD. It would be great to get a new release with all those dependency updates :)

**Comment by brettcannon** [comment]
I honestly haven't cut a new release since there hasn't been any logic changes since the first release (i.e., it ain't broke, so I didn't need to fix it 😉). But if it's becoming a problem for downstream packaging I can plan to make a new release.

But how far would you want me to go? For instance, `nix` has an available update, but it requires code changes to adapt to new APIs.

**Comment by decathorpe** [comment]
>  it ain't broke, so I didn't need to fix it 😉

True 😅

If something requires code changes, then it's fine with me if those dependency bumps don't happen before the next release. Getting a release with all the updated dependencies that are *already* on the main branch would already be a big step forward.

**Comment by brettcannon** [comment]
I'll see if I can update everything before EOM, else I will just cut a new release w/ what's on `main` as 1.0.1.

**Comment by decathorpe** [comment]
Awesome. Thank you!

**Comment by brettcannon** [comment]
1.0.1 is out!

https://github.com/brettcannon/python-launcher/releases/tag/v1.0.1

**Comment by decathorpe** [comment]
Thanks! I'll go ahead and close this issue :)
